[package]
name = "pikachu_matching"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14", features = ["png"] }   # Bevy 0.14 with PNG support

# Optional: web-sys / wasm-bindgen if you plan to compile to WASM
wasm-bindgen = "0.2"
